<?php

namespace Proxies\__CG__\Ben\DoctorsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Person extends \Ben\DoctorsBundle\Entity\Person implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'id', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'cin', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'cne', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'firstname', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'familyname', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'email', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'birthday', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'birthcity', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'gender', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'contry', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'city', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'address', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'etablissement', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'university', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'gsm', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'cnss', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'cnsstype', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'parentName', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'parentAddress', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'parentGsm', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'parentFixe', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'ishandicap', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'handicap', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'needs', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'resident', 'created', 'antecedents', 'consultations'];
        }

        return ['__isInitialized__', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'id', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'cin', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'cne', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'firstname', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'familyname', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'email', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'birthday', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'birthcity', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'gender', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'contry', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'city', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'address', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'etablissement', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'university', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'gsm', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'cnss', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'cnsstype', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'parentName', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'parentAddress', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'parentGsm', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'parentFixe', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'ishandicap', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'handicap', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'needs', '' . "\0" . 'Ben\\DoctorsBundle\\Entity\\Person' . "\0" . 'resident', 'created', 'antecedents', 'consultations'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Person $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setCin($cin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCin', [$cin]);

        return parent::setCin($cin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCin', []);

        return parent::getCin();
    }

    /**
     * {@inheritDoc}
     */
    public function setCne($cne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCne', [$cne]);

        return parent::setCne($cne);
    }

    /**
     * {@inheritDoc}
     */
    public function getCne()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCne', []);

        return parent::getCne();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', [$firstname]);

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', []);

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setFamilyname($familyname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFamilyname', [$familyname]);

        return parent::setFamilyname($familyname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFamilyname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFamilyname', []);

        return parent::getFamilyname();
    }

    /**
     * {@inheritDoc}
     */
    public function getFullName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullName', []);

        return parent::getFullName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthday($birthday)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthday', [$birthday]);

        return parent::setBirthday($birthday);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthday', []);

        return parent::getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthcity($birthcity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthcity', [$birthcity]);

        return parent::setBirthcity($birthcity);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthcity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthcity', []);

        return parent::getBirthcity();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', [$gender]);

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', []);

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setContry($contry)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContry', [$contry]);

        return parent::setContry($contry);
    }

    /**
     * {@inheritDoc}
     */
    public function getContry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContry', []);

        return parent::getContry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtablissement($etablissement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtablissement', [$etablissement]);

        return parent::setEtablissement($etablissement);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtablissement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtablissement', []);

        return parent::getEtablissement();
    }

    /**
     * {@inheritDoc}
     */
    public function setUniversity($university)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUniversity', [$university]);

        return parent::setUniversity($university);
    }

    /**
     * {@inheritDoc}
     */
    public function getUniversity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniversity', []);

        return parent::getUniversity();
    }

    /**
     * {@inheritDoc}
     */
    public function setGsm($gsm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGsm', [$gsm]);

        return parent::setGsm($gsm);
    }

    /**
     * {@inheritDoc}
     */
    public function getGsm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGsm', []);

        return parent::getGsm();
    }

    /**
     * {@inheritDoc}
     */
    public function setCnss($cnss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCnss', [$cnss]);

        return parent::setCnss($cnss);
    }

    /**
     * {@inheritDoc}
     */
    public function getCnss()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCnss', []);

        return parent::getCnss();
    }

    /**
     * {@inheritDoc}
     */
    public function setCnsstype($cnsstype)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCnsstype', [$cnsstype]);

        return parent::setCnsstype($cnsstype);
    }

    /**
     * {@inheritDoc}
     */
    public function getCnsstype()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCnsstype', []);

        return parent::getCnsstype();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentName($parentName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentName', [$parentName]);

        return parent::setParentName($parentName);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentName', []);

        return parent::getParentName();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentAddress($parentAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentAddress', [$parentAddress]);

        return parent::setParentAddress($parentAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentAddress', []);

        return parent::getParentAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentGsm($parentGsm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentGsm', [$parentGsm]);

        return parent::setParentGsm($parentGsm);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentGsm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentGsm', []);

        return parent::getParentGsm();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentFixe($parentFixe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentFixe', [$parentFixe]);

        return parent::setParentFixe($parentFixe);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentFixe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentFixe', []);

        return parent::getParentFixe();
    }

    /**
     * {@inheritDoc}
     */
    public function setResident($resident)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResident', [$resident]);

        return parent::setResident($resident);
    }

    /**
     * {@inheritDoc}
     */
    public function getResident()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResident', []);

        return parent::getResident();
    }

    /**
     * {@inheritDoc}
     */
    public function addAntecedent(\Ben\DoctorsBundle\Entity\Antecedent $antecedents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAntecedent', [$antecedents]);

        return parent::addAntecedent($antecedents);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAntecedent(\Ben\DoctorsBundle\Entity\Antecedent $antecedents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAntecedent', [$antecedents]);

        return parent::removeAntecedent($antecedents);
    }

    /**
     * {@inheritDoc}
     */
    public function getAntecedents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAntecedents', []);

        return parent::getAntecedents();
    }

    /**
     * {@inheritDoc}
     */
    public function addConsultation(\Ben\DoctorsBundle\Entity\Consultation $consultations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addConsultation', [$consultations]);

        return parent::addConsultation($consultations);
    }

    /**
     * {@inheritDoc}
     */
    public function removeConsultation(\Ben\DoctorsBundle\Entity\Consultation $consultations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeConsultation', [$consultations]);

        return parent::removeConsultation($consultations);
    }

    /**
     * {@inheritDoc}
     */
    public function getConsultations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsultations', []);

        return parent::getConsultations();
    }

    /**
     * {@inheritDoc}
     */
    public function setIshandicap($ishandicap)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIshandicap', [$ishandicap]);

        return parent::setIshandicap($ishandicap);
    }

    /**
     * {@inheritDoc}
     */
    public function getIshandicap()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIshandicap', []);

        return parent::getIshandicap();
    }

    /**
     * {@inheritDoc}
     */
    public function setHandicap($handicap)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHandicap', [$handicap]);

        return parent::setHandicap($handicap);
    }

    /**
     * {@inheritDoc}
     */
    public function getHandicap()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHandicap', []);

        return parent::getHandicap();
    }

    /**
     * {@inheritDoc}
     */
    public function setNeeds($needs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNeeds', [$needs]);

        return parent::setNeeds($needs);
    }

    /**
     * {@inheritDoc}
     */
    public function getNeeds()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNeeds', []);

        return parent::getNeeds();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

}
