<?php

namespace Ben\DoctorsBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TestController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/pacifik/Desktop/Doctors-master/app/cache/dev/jms_diextra/proxies/Ben-DoctorsBundle-Controller-TestController.php';
        $c = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Ben\\DoctorsBundle\\Controller\\TestController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'ajaxListAction' => array(0 => 'security.access.method_interceptor'), 'createAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'showAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'updateAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'), 'removeAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy32b63242_29a5223a14eae118be664aa104cc4f1f9e5a3900\__CG__\Ben\DoctorsBundle\Controller\TestController();
        $instance->__CGInterception__setLoader($c);
        return $instance;
    }
}
