<?php

namespace Ben\DoctorsBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PersonController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/pacifik/Desktop/Doctors-master/app/cache/dev/jms_diextra/proxies/Ben-DoctorsBundle-Controller-PersonController.php';
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Ben\\DoctorsBundle\\Controller\\PersonController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'ajaxListAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'showAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'updateAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'), 'removeAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy32b63242_dc2936259333934c76b0784f9540f8f4483401dc\__CG__\Ben\DoctorsBundle\Controller\PersonController();
        $instance->__CGInterception__setLoader($a);
        return $instance;
    }
}
